#!/usr/bin/env python3
"""Generate reduction-graph-data.js from reduction-graph.dot.

The .dot file is the source of truth for nodes (cluster, level color/style,
URL, tooltip, label) and edges; graphviz's layout provides the initial node
positions (dot -Tplain). Run from this directory:

    python3 gen-graph-data.py
"""
import json
import re
import subprocess

DOT = "reduction-graph.dot"
OUT = "reduction-graph-data.js"

LEVELS = {
    "#2a78d6": "core",
    "#1baf7a": "reducible",
    "#eda100": "expensive",
    "#4a3aa7": "aggressive",
    "#e34948": "removal",
}

src = open(DOT).read()

# ---- clusters and their nodes ----
nodes = {}
clusters = []
for m in re.finditer(r"subgraph cluster_(\w+) \{(.*?)\n  \}", src, re.S):
    cname, body = m.group(1), m.group(2)
    if cname == "legend":
        continue
    lab = re.search(r'label="([^"]*)"', body)
    clusters.append({"id": "cat_" + cname, "label": lab.group(1).replace("\\&", "&")})
    for nm in re.finditer(r"\n\s+(\w+)\s*\[(.*?)\];", body, re.S):
        name, attrs = nm.group(1), nm.group(2)
        def attr(key):
            a = re.search(key + r'="([^"]*)"', attrs)
            return a.group(1) if a else None
        color = attr("color") or "#2a78d6"
        style = attr("style") or ""
        label = attr("label") or name
        node = {
            "id": name,
            "parent": "cat_" + cname,
            "label": label.replace("\\n", "\n"),
            "level": LEVELS.get(color, "core"),
            "borderStyle": "double" if "peripheries=2" in attrs
                           else ("dashed" if "dashed" in style
                                 else ("dotted" if "dotted" in style else "solid")),
            "url": attr("URL"),
            "tooltip": (attr("tooltip") or "").replace("\\n", "\n"),
        }
        nodes[name] = node

# ---- positions and sizes from graphviz ----
plain = subprocess.run(["dot", "-Tplain", DOT], capture_output=True, text=True).stdout
maxy = 0.0
pos = {}
for line in plain.splitlines():
    parts = line.split()
    if parts and parts[0] == "node" and parts[1] in nodes:
        x, y, w, h = map(float, parts[2:6])
        pos[parts[1]] = (x, y, w, h)
        maxy = max(maxy, y)
S = 72.0  # inches -> px
for name, (x, y, w, h) in pos.items():
    nodes[name]["x"] = round(x * S, 1)
    nodes[name]["y"] = round((maxy - y) * S, 1)
    nodes[name]["w"] = round(w * S, 1)
    nodes[name]["h"] = round(h * S, 1)

# ---- edges (skip the legend's) ----
edges = []
for em in re.finditer(r"(\w+) -> (\w+)(\s*\[([^\]]*)\])?", src):
    a, b, attrs = em.group(1), em.group(2), em.group(4) or ""
    if a.startswith("l_") or b.startswith("l_"):
        continue
    lab = re.search(r'label="([^"]*)"', attrs)
    edges.append({
        "source": a,
        "target": b,
        "style": "dashed" if "dashed" in attrs else ("dotted" if "dotted" in attrs else "solid"),
        "label": (lab.group(1) if lab else "").replace("\\n", " ")
                 .replace("&rarr;", "→").replace("&forall;", "∀")
                 .replace("&exist;", "∃"),
    })

data = {"clusters": clusters, "nodes": list(nodes.values()), "edges": edges}
with open(OUT, "w") as f:
    f.write("// Generated by gen-graph-data.py from reduction-graph.dot — do not edit.\n")
    f.write("window.REDGRAPH = ")
    json.dump(data, f, ensure_ascii=False, indent=1)
    f.write(";\n")
print(f"{len(nodes)} nodes, {len(edges)} edges, {len(clusters)} clusters -> {OUT}")
